"""
Centralized UI offset configuration for all GUI screens.
"""

from __future__ import annotations

from typing import Dict, Tuple


UI_OFFSETS: Dict[str, Dict[str, Tuple[int, int] | int]] = {
    "menu": {
        "train": (0, 0),
        "evaluate": (0, 0),
        "demo": (0, 0),
        "replays": (0, 0),
        "setup": (0, 0),
        "options": (0, 0),
        "controls": (0, 0),
        "exit": (0, 0),
        "header": (0, 10),
        "button_size": (300, 108),
        "button_gap": 16,
        "header_size": (560, 170),
        "header_text_size": 110,
        "button_text_size": 36,
        "train_text_size": 44,
        "exit_size": (96, 48),
        "exit_text_size": 24,
    },
    "setup": {
        "back_pos": (34, 28),
        "back_size": (96, 46),
        "panel_margin": 34,
        "panel_top": 108,
        "panel_bottom_margin": 24,
        "left_panel_width": 392,
        "panel_gap": 20,
        "left_panel_offset": (0, 0),
        "right_panel_offset": (0, 0),
        "control_pad_x": 22,
        "control_start_y": 132,
        "row_gap": 78,
        "row_shift_y": 0,
        "seed_button_offset": (0, 10),
        "seed_button_w_pad": 44,
        "seed_button_h": 44,
        "pm_buttons_offset": (0, -20),
        "pm_button_size": (50, 44),
        "pm_x_gap": 238,
        "footer_from_bottom": 124,
        "preview_button_offset": (0, 30),
        "preview_button_w_pad": 44,
        "preview_button_h": 40,
        "preview_to_mini_gap": 48,
        "mini_buttons_w_pad": 52,
        "mini_button_h": 34,
        "mini_buttons_gap": 8,
        "refresh_button_offset": (0, 30),
        "save_button_offset": (0, 30),
        "preview_window_w": 860,
        "preview_window_h": 560,
        "preview_window_margin_w": 120,
        "preview_window_margin_h": 120,
        "preview_window_offset": (0, 0),
        "preview_close_size": (96, 36),
        "preview_close_inset": (22, 14),
        "title_offset": (0, 0),
        "seed_label_offset": (0, -30),
        "seed_value_offset": (0, -30),
        "control_row_label_offset": (0, -32),
        "control_row_value_offset": (0, 0),
        "right_info_offset": (0, 0),
        "right_info_gap": 34,
        "status_offset": (400, 0),
        "preview_header_offset": (0, 0),
        "preview_subheader_offset": (0, 0),
    },
    "train": {
        "back_button": (0, 0),
        "reset_button": (0, 0),
        "begin_button": (0, 0),
        "sub_toggle_button": (0, 0),
        "left_panel": (0, 0),
        "right_panel": (0, 0),
        "subwindow": (0, 0),
        "subwindow_close": (0, 0),
        "title": (0, 0),
        "status": (0, 0),
        "info_start": (0, -90),
        "subwindow_header": (0, 0),
        "subwindow_text": (0, 0),
    },
}
